version: '3.8'

services:
  prompt-manager:
    image: zhuchenyu2008/prompt-manage:latest
    ports:
      - "3501:3501"
    volumes:
      - prompt-data:/app/data
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  prompt-data:
